"use client";

import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FileText, Sparkles, Download } from "lucide-react";

type TemplateItem = {
  description: string
  quantity: number
  rate: number
}

type TemplateData = {
  currency: string
  items: TemplateItem[]
}

type Template = {
  id: string
  name: string
  data: TemplateData
  isAutoGenerated: boolean
  frequency: number | null
}

export function LoadTemplateDialog({
  onSelect,
}: {
  onSelect: (data: TemplateData) => void
}) {
  const [open, setOpen] = useState(false)
  const [templates, setTemplates] = useState<Template[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (open) {
      setLoading(true)
      fetch("/api/templates")
        .then((res) => res.json())
        .then((data) => {
          setTemplates(data)
          setLoading(false)
        })
    }
  }, [open])

  function handleSelect(t: Template) {
    onSelect(t.data)
    setOpen(false)
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" type="button">
          <Download className="size-4 mr-2" />
          Load template
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Select a template</DialogTitle>
        </DialogHeader>
        {loading ? (
          <p className="text-sm text-muted-foreground">Loading templates...</p>
        ) : templates.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No templates found. Create one in the Templates page.
          </p>
        ) : (
          <div className="space-y-3">
            {templates.filter((t) => t.isAutoGenerated).length > 0 && (
              <div>
                <p className="text-sm font-medium mb-2 flex items-center gap-1">
                  <Sparkles className="size-3 text-yellow-500" /> Auto-generated
                </p>
                <div className="grid gap-2">
                  {templates
                    .filter((t) => t.isAutoGenerated)
                    .map((t) => (
                      <TemplateItemCard key={t.id} template={t} onSelect={handleSelect} />
                    ))}
                </div>
              </div>
            )}
            <div>
              <p className="text-sm font-medium mb-2 flex items-center gap-1">
                <FileText className="size-3" /> Your templates
              </p>
              <div className="grid gap-2">
                {templates
                  .filter((t) => !t.isAutoGenerated)
                  .map((t) => (
                    <TemplateItemCard key={t.id} template={t} onSelect={handleSelect} />
                  ))}
              </div>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}

function TemplateItemCard({
  template,
  onSelect,
}: {
  template: Template
  onSelect: (t: Template) => void
}) {
  const total = (template.data.items || []).reduce((s, i) => s + i.quantity * i.rate, 0)
  return (
    <Card
      className="cursor-pointer hover:bg-accent transition-colors"
      onClick={() => onSelect(template)}
    >
      <CardContent className="p-3">
        <div className="flex items-center justify-between">
          <div>
            <p className="font-medium text-sm">{template.name}</p>
            <p className="text-xs text-muted-foreground">
              {template.data.currency} — {template.data.items?.length || 0} items — Total: {total.toLocaleString()}
            </p>
          </div>
          {template.frequency && (
            <Badge variant="secondary" className="text-xs">{template.frequency}x</Badge>
          )}
        </div>
        <div className="mt-1 text-xs text-muted-foreground">
          {template.data.items?.slice(0, 2).map((item, i) => (
            <span key={i} className="block">{item.description || "—"} x{item.quantity}</span>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}
