import { NextResponse } from "next/server";
import { prisma } from "@/app/utils/db";
import { requiredUser } from "@/app/utils/hooks";

export async function GET() {
  const session = await requiredUser();
  const userId = session.user?.id as string;

  const templates = await prisma.template.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      name: true,
      data: true,
      isAutoGenerated: true,
      frequency: true,
    },
  });

  return NextResponse.json(templates);
}
