"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createTemplate, deleteTemplate, generateAutoTemplates } from "@/app/actions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectItem,
  SelectContent,
} from "@/components/ui/select";
import { Trash2, Wand2, Plus, FileText, Sparkles, X, Eye } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

export type TemplateItem = {
  description: string
  quantity: number
  rate: number
}

export type TemplateData = {
  currency: string
  items: TemplateItem[]
}

export type Template = {
  id: string
  name: string
  data: TemplateData
  isAutoGenerated: boolean
  frequency: number | null
}

export function TemplateManager({ templates }: { templates: Template[] }) {
  const router = useRouter()
  const [showForm, setShowForm] = useState(false)
  const [list, setList] = useState(templates)
  const [saving, setSaving] = useState(false)
  const [name, setName] = useState("")
  const [currency, setCurrency] = useState("NPR")
  const [items, setItems] = useState<TemplateItem[]>([
    { description: "", quantity: 1, rate: 1 },
  ])

  useEffect(() => {
    setList(templates)
  }, [templates])

  function addItem() {
    setItems([...items, { description: "", quantity: 1, rate: 1 }])
  }

  function removeItem(index: number) {
    setItems(items.filter((_, i) => i !== index))
  }

  function updateItem(index: number, field: keyof TemplateItem, value: string | number) {
    const updated = [...items]
    updated[index] = { ...updated[index], [field]: value }
    setItems(updated)
  }

  async function handleCreate(formData: FormData) {
    formData.set("name", name)
    formData.set("currency", currency)
    formData.set("items", JSON.stringify(items))
    setSaving(true)
    const result = await createTemplate(undefined, formData)
    if ("type" in result) {
      toast.success(result.message)
      setShowForm(false)
      setName("")
      setCurrency("NPR")
      setItems([{ description: "", quantity: 1, rate: 1 }])
      router.refresh()
    }
    setSaving(false)
  }

  async function handleDelete(templateId: string) {
    const formData = new FormData()
    formData.set("id", templateId)
    const result = await deleteTemplate(formData)
    if (result.type === "success") {
      toast.success(result.message)
      setList((prev) => prev.filter((t) => t.id !== templateId))
    }
  }

  async function handleGenerate() {
    const result = await generateAutoTemplates()
    if (result.type === "success") {
      toast.success(result.message)
      router.refresh()
    } else {
      toast.error(result.message)
    }
  }

  const autoTemplates = list.filter((t) => t.isAutoGenerated)
  const userTemplates = list.filter((t) => !t.isAutoGenerated)

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Templates</h1>
          <p className="text-sm text-muted-foreground">
            Save invoice templates to reuse later
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleGenerate}>
            <Wand2 className="size-4 mr-2" />
            Generate from invoices
          </Button>
          <Button onClick={() => setShowForm(!showForm)}>
            <Plus className="size-4 mr-2" />
            New template
          </Button>
        </div>
      </div>

      {showForm && (
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Create template</CardTitle>
          </CardHeader>
          <CardContent>
            <form action={handleCreate} className="space-y-4">
              <div>
                <Label>Template name</Label>
                <Input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. Web Design Package"
                  required
                />
              </div>

              <div className="w-full max-w-xs">
                <Label>Currency</Label>
                <Select value={currency} onValueChange={setCurrency}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select currency" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="AUD">Australian Dollar -- AUD</SelectItem>
                    <SelectItem value="CAD">Canadian Dollar -- CAD</SelectItem>
                    <SelectItem value="CHF">Swiss Franc -- CHF</SelectItem>
                    <SelectItem value="CNY">Chinese Yuan -- CNY</SelectItem>
                    <SelectItem value="EUR">Euro -- EUR</SelectItem>
                    <SelectItem value="GBP">British Pound -- GBP</SelectItem>
                    <SelectItem value="INR">Indian Rupee -- INR</SelectItem>
                    <SelectItem value="JPY">Japanese Yen -- JPY</SelectItem>
                    <SelectItem value="NPR">Nepalese Rupee -- NPR</SelectItem>
                    <SelectItem value="USD">United States Dollar -- USD</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <div className="flex items-center justify-between mb-2">
                  <Label>Items</Label>
                  <Button type="button" variant="outline" size="sm" onClick={addItem}>
                    <Plus className="size-3 mr-1" /> Add item
                  </Button>
                </div>
                <div className="space-y-2">
                  {items.map((item, i) => (
                    <div key={i} className="flex gap-2 items-end">
                      <div className="flex-1">
                        {i === 0 && <p className="text-xs text-muted-foreground mb-1">Description</p>}
                        <Input
                          value={item.description}
                          onChange={(e) => updateItem(i, "description", e.target.value)}
                          placeholder="Item description"
                        />
                      </div>
                      <div className="w-24">
                        {i === 0 && <p className="text-xs text-muted-foreground mb-1">Qty</p>}
                        <Input
                          type="number"
                          value={item.quantity}
                          onChange={(e) => updateItem(i, "quantity", Number(e.target.value))}
                          onKeyDown={(e) => ["e", "E", "+", "-"].includes(e.key) && e.preventDefault()}
                          placeholder="1"
                        />
                      </div>
                      <div className="w-28">
                        {i === 0 && <p className="text-xs text-muted-foreground mb-1">Rate</p>}
                        <Input
                          type="number"
                          value={item.rate}
                          onChange={(e) => updateItem(i, "rate", Number(e.target.value))}
                          onKeyDown={(e) => ["e", "E", "+", "-"].includes(e.key) && e.preventDefault()}
                          placeholder="100"
                        />
                      </div>
                      <div className="w-20">
                        {i === 0 && <p className="text-xs text-muted-foreground mb-1">Amount</p>}
                        <Input
                          type="number"
                          value={item.quantity * item.rate}
                          readOnly
                          className="bg-muted"
                        />
                      </div>
                      {items.length > 1 && (
                        <Button type="button" variant="ghost" size="icon" onClick={() => removeItem(i)}>
                          <X className="size-4 text-red-500" />
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex justify-end border-t pt-4">
                <div className="w-1/3 text-right">
                  <p className="text-sm text-muted-foreground">Total</p>
                  <p className="text-lg font-semibold">
                    {currency} {items.reduce((sum, item) => sum + item.quantity * item.rate, 0).toLocaleString()}
                  </p>
                </div>
              </div>

              <Button type="submit" disabled={saving}>
                {saving ? "Saving..." : "Save template"}
              </Button>
            </form>
          </CardContent>
        </Card>
      )}

      {autoTemplates.length > 0 && (
        <div>
          <h2 className="text-lg font-medium mb-3 flex items-center gap-2">
            <Sparkles className="size-4 text-yellow-500" />
            Auto-generated
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {autoTemplates.map((t) => (
              <TemplateCard key={t.id} template={t} onDelete={handleDelete} />
            ))}
          </div>
        </div>
      )}

      <div>
        <h2 className="text-lg font-medium mb-3 flex items-center gap-2">
          <FileText className="size-4" />
          Your templates
        </h2>
        {userTemplates.length === 0 ? (
          <p className="text-sm text-muted-foreground">No templates yet. Create one above.</p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {userTemplates.map((t) => (
              <TemplateCard key={t.id} template={t} onDelete={handleDelete} />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

function TemplateCard({ template, onDelete }: { template: Template; onDelete: (id: string) => void }) {
  const [open, setOpen] = useState(false)
  const total = (template.data.items || []).reduce((s, i) => s + i.quantity * i.rate, 0)
  return (
    <>
      <Card className="cursor-pointer hover:bg-accent transition-colors" onClick={() => setOpen(true)}>
        <CardContent className="p-4">
          <div className="flex items-start justify-between">
            <div className="space-y-1">
              <h3 className="font-medium">{template.name}</h3>
              <p className="text-sm text-muted-foreground">
                {template.data.currency} — {template.data.items?.length || 0} item{(template.data.items?.length || 0) !== 1 ? "s" : ""}
              </p>
              {template.isAutoGenerated && template.frequency && (
                <Badge variant="secondary">Used {template.frequency} times</Badge>
              )}
            </div>
            <div className="flex gap-1" onClick={(e) => e.stopPropagation()}>
              <Button variant="ghost" size="icon" onClick={() => setOpen(true)}>
                <Eye className="size-4" />
              </Button>
              <Button variant="ghost" size="icon" onClick={() => onDelete(template.id)}>
                <Trash2 className="size-4 text-red-500" />
              </Button>
            </div>
          </div>
          <div className="mt-2 text-xs text-muted-foreground space-y-1">
            {template.data.items?.slice(0, 2).map((item, i) => (
              <p key={i}>{item.description || "—"} — {item.quantity} x {item.rate} = {item.quantity * item.rate}</p>
            ))}
            {(template.data.items?.length || 0) > 2 && (
              <p className="text-muted-foreground">+{template.data.items!.length - 2} more</p>
            )}
            <p className="font-medium text-sm pt-1">Total: {template.data.currency} {total.toLocaleString()}</p>
          </div>
        </CardContent>
      </Card>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              {template.name}
              {template.isAutoGenerated && (
                <Badge variant="secondary" className="text-xs">
                  <Sparkles className="size-3 mr-1" /> Auto
                </Badge>
              )}
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">Currency: {template.data.currency}</p>
            {template.frequency && (
              <p className="text-sm text-muted-foreground">Used in {template.frequency} invoices</p>
            )}

            <div className="border rounded-md">
              <div className="grid grid-cols-12 gap-2 px-3 py-2 bg-muted text-xs font-medium border-b">
                <p className="col-span-5">Description</p>
                <p className="col-span-2">Qty</p>
                <p className="col-span-2">Rate</p>
                <p className="col-span-3 text-right">Amount</p>
              </div>
              {template.data.items?.map((item, i) => (
                <div key={i} className="grid grid-cols-12 gap-2 px-3 py-2 text-sm border-b last:border-0">
                  <p className="col-span-5">{item.description || "—"}</p>
                  <p className="col-span-2">{item.quantity}</p>
                  <p className="col-span-2">{item.rate.toLocaleString()}</p>
                  <p className="col-span-3 text-right">{(item.quantity * item.rate).toLocaleString()}</p>
                </div>
              ))}
              <div className="grid grid-cols-12 gap-2 px-3 py-2 text-sm font-semibold border-t">
                <p className="col-span-9">Total</p>
                <p className="col-span-3 text-right">{template.data.currency} {total.toLocaleString()}</p>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
